server:
  port: 10000
spring:
  application:
    name: sparksession
  datasource:
    url: jdbc:mysql://47.103.96.236:8066/mycat_db01?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: 123456
  jpa:
    show-sql: true
  data:
    mongodb:
      uri: mongodb://shilin:123456@dds-uf625cb861ee57d41749-pub.mongodb.rds.aliyuncs.com:3717,dds-uf625cb861ee57d42404-pub.mongodb.rds.aliyuncs.com:3717,dds-uf625cb861ee57d43547-pub.mongodb.rds.aliyuncs.com:3717,dds-uf625cb861ee57d44752-pub.mongodb.rds.aliyuncs.com:3717,dds-uf625cb861ee57d45715-pub.mongodb.rds.aliyuncs.com:3717,dds-uf625cb861ee57d46289-pub.mongodb.rds.aliyuncs.com:3717/test?replicaSet=mgset-15204901
  rabbitmq:
    host: 47.103.47.188
    port: 15672
    username: guest
    password: guest
  redis:
    cluster:
      nodes:
        - 47.103.46.27:7001
        - 47.103.46.27:7002
        - 47.103.96.236:7001
        - 47.103.96.236:7002
        - 106.14.167.122:7001
        - 106.14.167.122:7002
      max-redirects: 3
    timeout: 10000
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 3
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://shilin...@12345678@127.0.0.1:8080/eureka/
mybatis:
  mapper-locations: classpath:com.witsion.sparksession.mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.witsion.sparksession.pojo
logging:
  level:
    com.witsion.sparksession.mapper: debug
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
